name: Publish Package to npmjs registry
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@Lysa14'
         
     
      - name: Install Dependencies
        run: |
             npm cache clean --force
             npm install
     
      - run: npm ci

      - name: Publish to npm
        run: |     
            npm publish --access public
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
# npm ci --ignore-scripts