name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
         
    strategy:
     matrix:
       architecture: [aarch64] # , x86_64
       ostype: [linux-gnu] # ,linux-musl
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

      - name: Archive the package
        if: ${{ needs.release.outputs.published == 'true' }}
        run: |
            tar -C package -czvf ${{ matrix.architecture }}-${{ matrix.ostype }}.tar.gz .
     
      - name: Add Release Artifact to the GitHub Release
        if: ${{ needs.release.outputs.published == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
              tag_name: ${{ needs.release.outputs.release-git-tag }}
              files: ${{ matrix.architecture }}-${{ matrix.ostype }}.tar.gz