name: Release

on:
  push:
    tags:
      - "*"   # Run on every commit tag which begins with "v" (e.g., "v0.1.4")
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
         
    strategy:
      matrix:
        architecture: [aarch64] # , x86_64
        ostype: [linux-gnu] # ,linux-musl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Release  
        id: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - name: Installer les dépendances
        run: |
          sudo apt update
          sudo apt install -y tar

      - name: Archive the package
        if: steps.release.outputs.published == 'true'
        run: |
          tar -czvf ${{ matrix.architecture }}-${{ matrix.ostype }}.tar.gz .

      - name: Add Release Artifact to the GitHub Release
        if: steps.release.outputs.published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.release-git-tag }}
          files: ${{ matrix.architecture }}-${{ matrix.ostype }}.tar.gz

