name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
 
    - name: Build
      run: |
        npm run build
      

    - name: Check for defined tests
      run: |
      
        test_files=$(find . -name '*spec*.js')
        if [ -z "$test_files" ]; then
          echo "Error: No test files found."
          exit 1
        fi

    - name: Run tests
      run: npm test
        
 
  send_email_notification:
        runs-on: ubuntu-latest
        needs: test
        if: ${{ needs.test.result == 'success' }}
        steps:
          - name: Send Email
            if: always()
            uses: hilarion5/send-mail@v1
            with:
              smtp-server: ${{ secrets.SMTP_NAME }}
              smtp-port: 2525
              smtp-secure: false
              from-email: ${{ secrets.FROM_EMAIL }}
              to-email: ${{ secrets.SMTP_TO_EMAIL }}
              username: ${{ secrets.SMTP_USERNAME }}
              password: ${{ secrets.SMTP_PASSWORD }}
              subject: Workflows Status Notifications
              body: |
                
                The build was ${{ needs.test.result }}.
                ----------------------------------------------
                Une nouvelle version de notre projet est disponible. Vous pouvez consulter la source du projet ici : https://github.com/${{ github.repository }}
                ---------------------------------------------      
        
  # Add the Cypress job for GUI tests
#  cypress:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2

 #   - name: Set up Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: '18'

#    - name: Install dependencies
#      run: npm instal
        
 #   - name: Install cypress
 #     run: npx cypress install

 #   - name: Run Cypress tests
 #     run: |
 #        npx cypress open --config baseUrl=http://localhost:3000
   #     npm run cypress:run


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Snyk test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # codacy-analysis-cli:
  #   name: Codacy Analysis CLI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@main

  #     - name: Run Codacy Analysis CLI
  #       uses: codacy/codacy-analysis-cli-action@master